package uk.nhs.nhsx.covid19.android.app.analytics

import uk.nhs.nhsx.covid19.android.app.analytics.legacy.AnalyticsMetricsStorage
import uk.nhs.nhsx.covid19.android.app.analytics.legacy.AnalyticsMetricsStorage.Companion.ANALYTICS_METRICS_KEY
import uk.nhs.nhsx.covid19.android.app.remote.data.Metrics
import uk.nhs.nhsx.covid19.android.app.util.ProviderTest
import uk.nhs.nhsx.covid19.android.app.util.ProviderTestExpectation
import uk.nhs.nhsx.covid19.android.app.util.ProviderTestExpectationDirection.OBJECT_TO_JSON

class AnalyticsMetricsStorageTest : ProviderTest<AnalyticsMetricsStorage, Metrics?>() {

    override val getTestSubject = ::AnalyticsMetricsStorage
    override val property = AnalyticsMetricsStorage::metrics
    override val key = ANALYTICS_METRICS_KEY
    override val defaultValue: Metrics? = null
    override val expectations: List<ProviderTestExpectation<Metrics?>> = listOf(
        ProviderTestExpectation(json = null, objectValue = null, direction = OBJECT_TO_JSON),
        ProviderTestExpectation(json = metricsJson, objectValue = metrics)
    )

    companion object {
        private val metricsJson =
            """
            {
            "canceledCheckIn":1,
            "checkedIn":2,
            "completedOnboarding":3,
            "completedQuestionnaireAndStartedIsolation":4,
            "completedQuestionnaireButDidNotStartIsolation":5,
            "cumulativeDownloadBytes":6,
            "cumulativeUploadBytes":7,
            "encounterDetectionPausedBackgroundTick":8,
            "hasHadRiskyContactBackgroundTick":9,
            "isIsolatingBackgroundTick":11,
            "receivedNegativeTestResult":12,
            "receivedPositiveTestResult":13,
            "receivedVoidTestResult":14,
            "receivedVoidTestResultEnteredManually":19,
            "receivedPositiveTestResultEnteredManually":17,
            "receivedNegativeTestResultEnteredManually":15,
            "receivedVoidTestResultViaPolling":20,
            "receivedPositiveTestResultViaPolling":18,
            "receivedNegativeTestResultViaPolling":16,
            "receivedVoidLFDTestResultEnteredManually":26,
            "receivedPositiveLFDTestResultEnteredManually":24,
            "receivedNegativeLFDTestResultEnteredManually":25,
            "receivedVoidLFDTestResultViaPolling":23,
            "receivedPositiveLFDTestResultViaPolling":21,
            "receivedNegativeLFDTestResultViaPolling":22,
            "receivedUnconfirmedPositiveTestResult":48,
            "receivedPositiveSelfRapidTestResultEnteredManually":54,
            "runningNormallyBackgroundTick":27,
            "totalBackgroundTasks":28,
            "hasSelfDiagnosedBackgroundTick":29,
            "hasTestedPositiveBackgroundTick":30,
            "hasTestedLFDPositiveBackgroundTick":31,
            "hasTestedSelfRapidPositiveBackgroundTick":55,
            "isIsolatingForSelfDiagnosedBackgroundTick":32,
            "isIsolatingForTestedPositiveBackgroundTick":33,
            "isIsolatingForTestedLFDPositiveBackgroundTick":34,
            "isIsolatingForTestedSelfRapidPositiveBackgroundTick":56,
            "isIsolatingForUnconfirmedTestBackgroundTick":49,
            "isIsolatingForHadRiskyContactBackgroundTick":35,
            "receivedRiskyContactNotification":36,
            "startedIsolation":37,"receivedActiveIpcToken":38,
            "haveActiveIpcTokenBackgroundTick":39,
            "selectedIsolationPaymentsButton":40,
            "launchedIsolationPaymentsApplication":41,
            "launchedTestOrdering":42,
            "totalExposureWindowsNotConsideredRisky":43,
            "totalExposureWindowsConsideredRisky":44,
            "acknowledgedStartOfIsolationDueToRiskyContact":45,
            "hasRiskyContactNotificationsEnabledBackgroundTick":46,
            "totalRiskyContactReminderNotifications":47,
            "didHaveSymptomsBeforeReceivedTestResult":51,
            "didRememberOnsetSymptomsDateBeforeReceivedTestResult":52,
            "didAskForSymptomsOnPositiveTestEntry":53,
            "receivedRiskyVenueM1Warning":57,
            "receivedRiskyVenueM2Warning":58,
            "hasReceivedRiskyVenueM2WarningBackgroundTick":59,
            "totalAlarmManagerBackgroundTasks":60,
            "missingPacketsLast7Days":61,
            "askedToShareExposureKeysInTheInitialFlow":62,
            "consentedToShareExposureKeysInTheInitialFlow":63,
            "successfullySharedExposureKeys":64,
            "totalShareExposureKeysReminderNotifications":65,
            "consentedToShareExposureKeysInReminderScreen":66,
            "didSendLocalInfoNotification":67,
            "didAccessLocalInfoScreenViaNotification":68,
            "didAccessLocalInfoScreenViaBanner":69,
            "isDisplayingLocalInfoBackgroundTick":70,
            "positiveLabResultAfterPositiveLFD":71,
            "negativeLabResultAfterPositiveLFDWithinTimeLimit":72,
            "negativeLabResultAfterPositiveLFDOutsideTimeLimit":73,
            "positiveLabResultAfterPositiveSelfRapidTest":74,
            "negativeLabResultAfterPositiveSelfRapidTestWithinTimeLimit":75,
            "negativeLabResultAfterPositiveSelfRapidTestOutsideTimeLimit":76,
            "didAccessRiskyVenueM2Notification":77,
            "selectedTakeTestM2Journey":78,
            "selectedTakeTestLaterM2Journey":79,
            "selectedHasSymptomsM2Journey":80,
            "selectedHasNoSymptomsM2Journey":81,
            "selectedLFDTestOrderingM2Journey":82,
            "selectedHasLFDTestM2Journey":83,
            "optedOutForContactIsolation":84,
            "optedOutForContactIsolationBackgroundTick":85,
            "appIsUsableBackgroundTick":86,
            "appIsUsableBluetoothOffBackgroundTick":89,
            "appIsContactTraceableBackgroundTick":87,
            "didAccessSelfIsolationNoteLink":88,
            "completedV2SymptomsQuestionnaire":90,
            "completedV2SymptomsQuestionnaireAndStayAtHome":91,
            "hasCompletedV2SymptomsQuestionnaireBackgroundTick":92,
            "hasCompletedV2SymptomsQuestionnaireAndStayAtHomeBackgroundTick":93
            }
            """.trimIndent().replace("\n", "")
        private val metrics = Metrics(
            canceledCheckIn = 1,
            checkedIn = 2,
            completedOnboarding = 3,
            completedQuestionnaireAndStartedIsolation = 4,
            completedQuestionnaireButDidNotStartIsolation = 5,
            cumulativeDownloadBytes = 6,
            cumulativeUploadBytes = 7,
            encounterDetectionPausedBackgroundTick = 8,
            hasHadRiskyContactBackgroundTick = 9,
            isIsolatingBackgroundTick = 11,
            receivedNegativeTestResult = 12,
            receivedPositiveTestResult = 13,
            receivedVoidTestResult = 14,
            receivedNegativeTestResultEnteredManually = 15,
            receivedNegativeTestResultViaPolling = 16,
            receivedPositiveTestResultEnteredManually = 17,
            receivedPositiveTestResultViaPolling = 18,
            receivedVoidTestResultEnteredManually = 19,
            receivedVoidTestResultViaPolling = 20,
            receivedPositiveLFDTestResultViaPolling = 21,
            receivedNegativeLFDTestResultViaPolling = 22,
            receivedVoidLFDTestResultViaPolling = 23,
            receivedPositiveLFDTestResultEnteredManually = 24,
            receivedNegativeLFDTestResultEnteredManually = 25,
            receivedVoidLFDTestResultEnteredManually = 26,
            runningNormallyBackgroundTick = 27,
            totalBackgroundTasks = 28,
            hasSelfDiagnosedBackgroundTick = 29,
            hasTestedPositiveBackgroundTick = 30,
            hasTestedLFDPositiveBackgroundTick = 31,
            isIsolatingForSelfDiagnosedBackgroundTick = 32,
            isIsolatingForTestedPositiveBackgroundTick = 33,
            isIsolatingForTestedLFDPositiveBackgroundTick = 34,
            isIsolatingForHadRiskyContactBackgroundTick = 35,
            receivedRiskyContactNotification = 36,
            startedIsolation = 37,
            receivedActiveIpcToken = 38,
            haveActiveIpcTokenBackgroundTick = 39,
            selectedIsolationPaymentsButton = 40,
            launchedIsolationPaymentsApplication = 41,
            launchedTestOrdering = 42,
            totalExposureWindowsNotConsideredRisky = 43,
            totalExposureWindowsConsideredRisky = 44,
            acknowledgedStartOfIsolationDueToRiskyContact = 45,
            hasRiskyContactNotificationsEnabledBackgroundTick = 46,
            totalRiskyContactReminderNotifications = 47,
            receivedUnconfirmedPositiveTestResult = 48,
            isIsolatingForUnconfirmedTestBackgroundTick = 49,
            didHaveSymptomsBeforeReceivedTestResult = 51,
            didRememberOnsetSymptomsDateBeforeReceivedTestResult = 52,
            didAskForSymptomsOnPositiveTestEntry = 53,
            receivedPositiveSelfRapidTestResultEnteredManually = 54,
            hasTestedSelfRapidPositiveBackgroundTick = 55,
            isIsolatingForTestedSelfRapidPositiveBackgroundTick = 56,
            receivedRiskyVenueM1Warning = 57,
            receivedRiskyVenueM2Warning = 58,
            hasReceivedRiskyVenueM2WarningBackgroundTick = 59,
            totalAlarmManagerBackgroundTasks = 60,
            missingPacketsLast7Days = 61,
            askedToShareExposureKeysInTheInitialFlow = 62,
            consentedToShareExposureKeysInTheInitialFlow = 63,
            successfullySharedExposureKeys = 64,
            totalShareExposureKeysReminderNotifications = 65,
            consentedToShareExposureKeysInReminderScreen = 66,
            didSendLocalInfoNotification = 67,
            didAccessLocalInfoScreenViaNotification = 68,
            didAccessLocalInfoScreenViaBanner = 69,
            isDisplayingLocalInfoBackgroundTick = 70,
            positiveLabResultAfterPositiveLFD = 71,
            negativeLabResultAfterPositiveLFDWithinTimeLimit = 72,
            negativeLabResultAfterPositiveLFDOutsideTimeLimit = 73,
            positiveLabResultAfterPositiveSelfRapidTest = 74,
            negativeLabResultAfterPositiveSelfRapidTestWithinTimeLimit = 75,
            negativeLabResultAfterPositiveSelfRapidTestOutsideTimeLimit = 76,
            didAccessRiskyVenueM2Notification = 77,
            selectedTakeTestM2Journey = 78,
            selectedTakeTestLaterM2Journey = 79,
            selectedHasSymptomsM2Journey = 80,
            selectedHasNoSymptomsM2Journey = 81,
            selectedLFDTestOrderingM2Journey = 82,
            selectedHasLFDTestM2Journey = 83,
            optedOutForContactIsolation = 84,
            optedOutForContactIsolationBackgroundTick = 85,
            appIsUsableBackgroundTick = 86,
            appIsContactTraceableBackgroundTick = 87,
            didAccessSelfIsolationNoteLink = 88,
            appIsUsableBluetoothOffBackgroundTick = 89,
            completedV2SymptomsQuestionnaire = 90,
            completedV2SymptomsQuestionnaireAndStayAtHome = 91,
            hasCompletedV2SymptomsQuestionnaireBackgroundTick = 92,
            hasCompletedV2SymptomsQuestionnaireAndStayAtHomeBackgroundTick = 93
        )
    }
}
